### ISSUE TITLE
Consider using YAML::PP

### ISSUE THREAD

**Issue by perlpunk** [XSven/Log-Log4perl-Config-YamlConfigurator#1]
Hi,
I just saw your module popping up in https://www.perl.com/article/what-s-new-on-cpan-may-2024/ and saw that it's using YAML.pm.
Nowadays I would recommend to use YAML::PP, as it is also recommended in the YAML.pm docs:
https://metacpan.org/dist/YAML/view/lib/YAML.pod#IMPORTANT-PLEASE-READ-THIS-FIRST

**Comment by XSven** [comment]
I have developed the Log4perl YamlConfigurator because I wanted to initialize logging using a nested `Beam::Wire` container file (have a look at _t/init_with_beam_wire.t_). `Beam::Wire` uses `Config::Any::YAML` that uses _YAML.pm_ as its final fallback ([requires_any_of](https://metacpan.org/pod/Config::Any::YAML#requires_any_of(-))). To avoid the use of multiple YAML backends I have used _YAML.pm_ too. What's missing is a _YAML.pm_ fake that shadows (== marks as loaded) the `YAML` module and that behaves like `YAML::PP` behind the scenes. Your comment is appreciated!

**Comment by XSven** [comment]
fixed in new 1.0.1 release that was just uploaded to CPAN
